name: Build using esy

on:
  pull_request:
  push:
    branches:
      - fork

jobs:
  build:
    name: Build

    strategy:
      matrix:
        system: [windows]

    runs-on: ${{ matrix.system }}-latest

    steps:
    - name: Check LongPathsEnabled
      run: |
        (Get-ItemProperty "HKLM:System\CurrentControlSet\Control\FileSystem").LongPathsEnabled
     
